### ISSUE TITLE
Can't build it

### ISSUE THREAD

**Issue by SarkarKurdish** [mab-on/cpe#1]
Sorry if my issue is too obvious I have no idea how to use D lang.

I have cloned this project installed D-lang and tried to build it with this command
`dmd source/app.d` or `dmd app.d`
and I've got this error
```bash
lld-link: error: undefined symbol: __D6libcpe6client4scan3appFAAyaZi
>>> referenced by app.obj:(__D3app4mainFAAyaZ8dispatchMFQqZv)

lld-link: error: undefined symbol: __D6libcpe6client4list3appFAAyaZi
>>> referenced by app.obj:(__D3app4mainFAAyaZ8dispatchMFQqZv)

lld-link: error: undefined symbol: __D6libcpe6client4call3appFAAyaZi
>>> referenced by app.obj:(__D3app4mainFAAyaZ8dispatchMFQqZv)

lld-link: error: undefined symbol: __D6libcpe6client7profile4core3appFAAyaZv
>>> referenced by app.obj:(__D3app4mainFAAyaZ8dispatchMFQqZv)

lld-link: error: undefined symbol: __D6libcpe6client4list12__ModuleInfoZ
>>> referenced by app.obj:(__D3app12__ModuleInfoZ)
Error: linker exited with status 1

```

**Comment by SarkarKurdish** [comment]
The first run was done on windows, and I've tried Ubuntu(WSL) this was the error

```bash
app.o:(.data.rel.ro+0x10): undefined reference to `_D6libcpe6client4list12__ModuleInfoZ'
app.o: In function `_D3app4mainFAAyaZ8dispatchMFQqZv':
app.d:(.text._D3app4mainFAAyaZ8dispatchMFQqZv[_D3app4mainFAAyaZ8dispatchMFQqZv]+0x7a): undefined reference to `_D6libcpe6client4scan3appFAAyaZi'
app.d:(.text._D3app4mainFAAyaZ8dispatchMFQqZv[_D3app4mainFAAyaZ8dispatchMFQqZv]+0x93): undefined reference to `_D6libcpe6client4list3appFAAyaZi'
app.d:(.text._D3app4mainFAAyaZ8dispatchMFQqZv[_D3app4mainFAAyaZ8dispatchMFQqZv]+0xac): undefined reference to `_D6libcpe6client4call3appFAAyaZi'
app.d:(.text._D3app4mainFAAyaZ8dispatchMFQqZv[_D3app4mainFAAyaZ8dispatchMFQqZv]+0xc5): undefined reference to `_D6libcpe6client7profile4core3appFAAyaZv'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```

**Comment by mab-on** [comment]
Hi, you should use Linux or MS WSL, i have not implemented MS Windows support.

I do recommend you use [the official install-script](https://dlang.org/install.html#get_posix) to install the complier "dmd" and its package manager "dub".
Simply use this bash command as a non-root user to download the install-script and install the latest dmd compiler: 
`curl https://dlang.org/install.sh | bash -s`
This will install dlang under `~/dlang/` - after that you only need to activate it for your currrent bash session: Run `source ~/dlang/dmd-2.106.1/activate` in your shell to use dmd-2.106.1.

Now you can go to the directory, where you git-cloned the repo and do `dub build`. dub will download the dependencies and compile the source code. The result will be the "cpe" binary app than you can use as described in the readme - or do e.g. `./cpe -h`, `./cpe profile -h` etc.  

Oh! And make sure to pull the latest commits in the master branch - I made a fix today which is needed for a recent version of dmd.

**Comment by SarkarKurdish** [comment]
@mab-on Thanks for the installation guide it worked as intended much appreciated
